### ISSUE TITLE
00-Showcase: Super ugly with dark GTK themes

### ISSUE THREAD

**Issue by TiZ-EX1** [ianharrigan/hxWidgets#10]
See attached image. I don't know if there's something the sample app has to do or something the bindings have to do, but I figured I'd report anyways. I hope the onslaught of issue submissions are more helpful than annoying. :)

![20160210-102216](https://cloud.githubusercontent.com/assets/4130673/12951496/99369152-cfe0-11e5-8451-4f2afe28bf88.png)

**Comment by ianharrigan** [comment]
What happens if you remove this line: https://github.com/ianharrigan/hxWidgets/blob/master/samples/00-Showcase/src/Main.hx#L12

**Comment by TiZ-EX1** [comment]
Much better! That's an easy catch, I feel silly for not checking for it myself, haha.
![20160210-103202](https://cloud.githubusercontent.com/assets/4130673/12951735/b401a372-cfe1-11e5-8ada-e1188b6f8162.png)

**Comment by ianharrigan** [comment]
To be honest, its my fault really i think i just did it to test it worked, ie 0xFF0000 and then just left it there with a different colour... I noticed similar issues on my linux and mac, ie, it wasnt gray but was white and didnt bother to change it.

**Comment by TiZ-EX1** [comment]
Well, at least now we know we can do it!

**Comment by ianharrigan** [comment]
PS: yes, the "onslaught of issues" is certainly helpful - the definite aim hxWidgets is that it will be community driven as generating the full hxWidgets lib externs / wrappers isnt feasible at this time so the more issues and PRs the better in my book.

**Comment by ianharrigan** [comment]
PPS: im not quite sure how you dont go blind looking at the screen with that theme! :)

**Comment by TiZ-EX1** [comment]
It's very relaxing to my eyes, actually. :)

**Comment by ianharrigan** [comment]
So this is crappy, if you remove that background color from windows: 
![image](https://cloud.githubusercontent.com/assets/3024242/12953252/dde15998-d019-11e5-94d4-a7f92ccb8234.png)

**Comment by TiZ-EX1** [comment]
That looks like an upstream issue to me.

**Comment by ianharrigan** [comment]
yeah... Would be nice to somehow fix it though... :/

**Comment by TiZ-EX1** [comment]
Probably only a W10 problem. Is it possible to detect W10 and conditionally make the background white?

**Comment by ianharrigan** [comment]
Ill have to research and see...

**Comment by ianharrigan** [comment]
Ok, i added PlatformInfo, so can now use: https://github.com/ianharrigan/hxWidgets/commit/0346cf1a91f9f5c47b97bed3e85dd2996a484d54#diff-a1fcf8448c18d2a9b1041ad5e59d5f7eR21

Think this is safe to close?

**Comment by ianharrigan** [comment]
Subtle, but worth it: 

Before:
![image](https://cloud.githubusercontent.com/assets/3024242/12955377/052db16e-d023-11e5-9c09-0778b53c7c49.png)

After:
![image](https://cloud.githubusercontent.com/assets/3024242/12955383/0aa2092e-d023-11e5-9ce6-e81725edac16.png)

**Comment by TiZ-EX1** [comment]
Yeah, that's definitely better, though I'd hazard a guess that not all versions of windows want a white background. I'd probably keep it to 8 or above. Looks like PlatformInfo has code to check that.

**Comment by ianharrigan** [comment]
Yeah, its just the sample app of course, so i dont think its a major issue to make everything "perfect". Thats more up to anyone writing a "real" application. The important point is that its possible to distinguish between running platforms and modify the UI accordingly.

**Comment by TiZ-EX1** [comment]
Fair counterpoint. I'd say we're good here, then.
