### ISSUE TITLE
More than one version of the MSVC compiler causes empty folder issue in Build.xml

### ISSUE THREAD

**Issue by tienery** [ianharrigan/hxWidgets#18]
If you have more than one version of the MSVC compiler installed on your computer, the compile results in a linking error which is as a result of an empty string being passed into where `${vc}` is.

I haven't actually tested to see if it is because I have more than one version installed or because of some other inexplicible reason, but my temporary solution is simply to replace the value with `v120`.

It's only a minor gripe, I'm not hugely concerned, but it can be rather annoying, particularly when updating and forgetting to modify the file.

**Comment by ianharrigan** [comment]
I think hxcpp set this var, so it might be worth investigating where that comes from. Also, you could try to set an environment var and see if that fixes it.

**Comment by ibilon** [comment]
The build file doesn't use this var anymore.
