### ISSUE TITLE
Missing elements

### ISSUE THREAD

**Issue by sumo961** [ianharrigan/hxWidgets#23]
Looking through the code more, there are several missing elements on OS X/wxwidgets 3.0.2:

- no buttons on tabs 2 or 3 (but buttons in tab 1 are fine)
- Open GL window has no content
- The DC draw elements on the panel are missing (and is there initially supposed to be a blue line on a blue background?)
- none of the images work (there is a warning initially about "invalid format")

**Comment by ianharrigan** [comment]
Ill have to double check the other issues, though i dont remember them being issues (although im using a mac vm so not sure if that could be related). 

However, as you mentioned i have noticed the DC stuff not working at all on mac / linux, which ive been meaning to take another look at. Unfortunately time isnt my friend at the moment.

**Comment by sumo961** [comment]
Thanks.

One thing - are you using WXwidgets 3.0.2 or 3.1?

Another thing - could some things be ported over from the waxe project? I
think you're approach is quite different how you make the "glue", so I'm
not sure. One nice thing waxe had, was a way to handle OS X Menu items like
this:

        //file.append(App.s_macAboutMenuItemId, "About Simple.hx");
        //file.append(App.s_macPreferencesMenuItemId, "Preferences of
Simple.hx");
        //file.append(App.s_macExitMenuItemId, "Exit");

**Comment by ianharrigan** [comment]
Ok, so as far as the menus go you have a few options now:

```haxe
        file.appendItem(new MenuItem(file, null, null, StandardIds.ABOUT));
        file.appendItem(new MenuItem.PreferencesMenuItem(file));
        file.append(StandardIds.EXIT);
```

**Comment by sumo961** [comment]
Updated list of what works/what's missing on my system

- images are all there now!
- Most of the DC stuff works

What's missing:
- Second vertical slider is not there (but I do see only the text 100 50 0 underneath a radio button)
- "Test" DC element does not show
- Open Gl button is invisible, appears once position is clicked
- Open Gl window is just grey
- Buttons on Tab 2 and 3 still missing

Thanks - keep up the good work

**Comment by ianharrigan** [comment]
Ok, great... slowly moving forward! :)

Any chance you can send a screen shot? It might just be that some controls are underneath other controls. Also I had to remove the menu stuff i detailed above as it didnt seem available in linux, so will have to rethink it somewhat. Still, progress is progress.

Cheers,
Ian

**Comment by ianharrigan** [comment]
(Also you might want to grab the latest ive just pushed also)

**Comment by sumo961** [comment]
Cool - further improvements:

DC area now has red background and text "Test" appears.

Other issues still exist including the strange "openFL button only become
visible once clicked on"

Cheers,

Hartmut

**Comment by ianharrigan** [comment]
Have you got a screen shot btw? Just want to check something.

**Comment by sumo961** [comment]
It seems I cannot sent screenshots here.

https://www.dropbox.com/s/olckp6o2im0d4hi/Bildschirmfoto%202016-04-27%20um%2011.48.48.png?dl=0

https://www.dropbox.com/s/o2gvfcy0esl19v0/Bildschirmfoto%202016-04-26%20um%2019.32.26.png?dl=0

**Comment by ianharrigan** [comment]
Hi Sumo,

When you get a moment can you pull latest demo and try again... one thing to now about this is that the "drawing" page doesnt work. Im not quite sure what it is, but something strange happens on osx. But you should be able to flip between the pages now and see components. Bizarrely the event handler for the event when the notebook page changed needed an `e.skip()` - not totally sure why, but my guess is that it was "eating" the event so the OS never knew it had been changed and thus to relayout everything - not sure. 

Anyways, let me know if it works (screen shot would be good too!)

**Comment by sumo961** [comment]
Right now I get a compile error - do I need a different version of hxcpp?

./src/hx/widgets/TextCtrl.cpp:46:16: error: ambiguous conversion for functional-style cast from 'Pointer<wxTextCtrl>' to '::cpp::Pointer<wxWindow>'

**Comment by ianharrigan** [comment]
you need git version of hxcpp

**Comment by sumo961** [comment]
but which version? - The version I have worked before

**Comment by ibilon** [comment]
The latest commit,
a lot was fixed and added.

**Comment by sumo961** [comment]
OK, I got it running now. 

First tab: the multiline text control is "smashed" and nothing on drawing tap other than black background.

Console shows: 
12:48:12: Debug: wxColour::Set - couldn't set to colour string 'CYAN'
12:48:12: Debug: wxColour::Set - couldn't set to colour string 'GREY'
12:48:12: Debug: wxColour::Set - couldn't set to colour string 'LIGHT GREY'
12:48:12: Debug: wxColour::Set - couldn't set to colour string 'MEDIUM GREY'

![bildschirmfoto 2016-05-08 um 12 45 54](https://cloud.githubusercontent.com/assets/11142464/15099338/9976ecea-1520-11e6-80b9-331039c61dd6.png)
![bildschirmfoto 2016-05-08 um 12 44 52](https://cloud.githubusercontent.com/assets/11142464/15099339/99815716-1520-11e6-8ac3-e964c3e881f6.png)
![bildschirmfoto 2016-05-08 um 12 44 39](https://cloud.githubusercontent.com/assets/11142464/15099340/9982bef8-1520-11e6-8733-418bb93ba72c.png)

**Comment by ianharrigan** [comment]
Yeah, ive noticed those two issues on my VM too... Something to do with the sizers (for the text field) and not sure about the drawing dialog... seems like the paint isnt handled correctly... Still, apart from that looking pretty good.

**Comment by sumo961** [comment]
Yes, definitely progress. Keep up the good work. 

Here are two questions: 
- will there be native file dialogs?

- will drag and drop be possible?

Von meinem iPhone gesendet

**Comment by ibilon** [comment]
> - will there be native file dialogs?
- will drag and drop be possible?

wxWidgets supports both of these, and they are useful, so yes ;)

**Comment by sumo961** [comment]
Great!

**Comment by ianharrigan** [comment]
Ok, so i think im going to close this issue and open up new ones about the text field and drawing... As well as some feature requests for file dialogs and drag and drop... Ok with you @sumo961?

**Comment by ianharrigan** [comment]
Here are the new issues:

* https://github.com/ianharrigan/hxWidgets/issues/27
* https://github.com/ianharrigan/hxWidgets/issues/28
* https://github.com/ianharrigan/hxWidgets/issues/29
* https://github.com/ianharrigan/hxWidgets/issues/30

**Comment by sumo961** [comment]
Sounds good

Von meinem iPhone gesendet
