### ISSUE TITLE
Feature request: file dialogs

### ISSUE THREAD

**Issue by ianharrigan** [ianharrigan/hxWidgets#29]

**Comment by ibilon** [comment]
Note: the FileDialog class now exists but is lacking the required functions to be useful.

**Comment by tienery** [comment]
Don't see a point in File Dialogs since Linc Dialogs exist: https://github.com/snowkit/linc_dialogs

**Comment by ianharrigan** [comment]
... then dont use it?

**Comment by ibilon** [comment]
Because you don't need another library? Because it's part of the wxWidgets' API?

> ... then dont use it?

or that :p

**Comment by tienery** [comment]
I was just pointing it out, I didn't say I did use File Dialogs now did I? ;)

**Comment by ianharrigan** [comment]
Well, thanks for letting us know that you dont use it or plan to use it as you dont see the see the point in using it. :)

**Comment by ibilon** [comment]
Thanks to @mrcdk the class can be used now.
